### ISSUE TITLE
Option to switch Ctrl and Fn Keys?

### ISSUE THREAD

**Issue by Dunkeeel** [samartzidis/WinAppleKey#10]
Is it possible to change the Ctrl and the Fn key like in WinA1314? Like with a registry edit or sth like that?
Got so used to the keys being the same as keyboard layout actually says.

Apart from that, this driver seems to work much better 👍 
So, thanks for the great work!

**Comment by zzuper** [comment]
Yeah, what happaned with that..        :  ]

**Comment by samartzidis** [comment]
This is now addressed in release 1.0.3. Thanks.

**Comment by Hubro** [comment]
Works perfectly, thanks!
