### ISSUE TITLE
Mapping Windows and Option Keys

### ISSUE THREAD

**Issue by bsnider** [samartzidis/WinAppleKey#14]
@samartzidis This driver is just about what I'm looking for!

I'm curious if it's possible to re-map the command and option keys so that

```
Input physical key   -->   Output logical key
Left Option (Alt)    -->   Win
Left Command         -->   Alt
Right Command        -->   Alt
Right Option (Alt)   -->   Ctrl
```

This way, the Apple Magic Keyboard 2 keys would exactly match a Windows keyboard layout.

Thanks!

**Comment by RailRanger** [comment]
You can use sharpkeys to do that
