### ISSUE TITLE
Visual Studio 2015 Build Error

### ISSUE THREAD

**Issue by winappkey** [samartzidis/WinAppleKey#15]
I get the following error when I try to build the WinAppleKey project:

Severity	Code	Description	Project	File	Line	Suppression State
Error	1218	Invalid driver date value ?07?/?11?/?1.16.46.318 in Version, expecting MM/DD/YYYY.	WinAppleKey	C:\WinAppleKey\WinAppleKey\WinAppleKey.inf	12

Line 12 of the INF file is commented out in the version I downloaded from Github:  

;DriverVer=01/04/2017, 1.0.0.0  (notice the semicolon)

The date looks like it is in the required format.  I have tried uncommenting the line, changing the date to the current date, setting the /uselocaltime flag for INF2CAT tool under the project properties, running Visual Studio as administrator, and changing the version to 1.0.3.0 (which is the file version reported in the resource file).

All to no avail !!!

Any suggestions?

**Comment by samartzidis** [comment]
Fixed. Thanks!
