### ISSUE TITLE
Media Keys?

### ISSUE THREAD

**Issue by lanslans** [samartzidis/WinAppleKey#26]
Can this be an option, either at the time of install or configurable through registry?

I got keycodes from here: https://source.android.com/devices/input/keyboard-devices.html#hid-keyboard-and-keypad-page-0x07

Maybe I'm missing something, but I can't seem to get this to work. I've tried this within the function key section
```
                case HidF7: TmpBuf[4] = 0xEA; break;
                case HidF8: TmpBuf[4] = 0E9; break;
                case HidF9: TmpBuf[4] = 0xEB; break;
                case HidF10: TmpBuf[4] = 0x7F; break;
                case HidF11: TmpBuf[4] = 0x81; break;
                case HidF12: TmpBuf[4] = 0x80; break;
```

I've tried this right below the eject/delete key code too.

   ```
    if (buf[2] & 0x8) //Eject
            SpecialKey = HidDel; //Del	

        switch (buf[2]) {
            case HidF7: buf[2] = 0xEA; break;
            case HidF8: buf[2] = 0E9; break;
            case HidF9: buf[2] = 0xEB; break;
            case HidF10: buf[2] = 0x7F; break;
            case HidF11: buf[2] = 0x81; break;
            case HidF12: buf[2] = 0x80; break;
        }
```
I've tried TmpBuf[2] above and buf[4] here - I'm mostly shooting blind, I really have no knowledge here of HID devices, windows drivers, or how the rest of the driver works.

Any suggestions?

Fn+other keys work, but I can't get these to.

**Comment by samartzidis** [comment]
@lanslans, you were looking at the right location but the media keys are routed through a different HID report id and not through the standard keys report id. There is significantly more work needed in getting them to work with this rather simplistic driver. I have no plans in implementing this at the moment as I spend most of my available time in the newer RaspiKey project.
