### ISSUE TITLE
hello，i want to know what's the difference in the new update

### ISSUE THREAD

**Issue by lukiolee** [samartzidis/WinAppleKey#32]
Just as the title.

**Comment by samartzidis** [comment]
Hi @lukiolee.  There was a potential problem with the installer in the previous release so I rebuilt it with newly issued test certificates. If the 1.0.5 install you currently have works fine for you you do not need to update.

**Comment by lukiolee** [comment]
hello samartzidis:
 Thanks for  your work so much, i've used 1.0.4 for a long time, it also work well.
