### ISSUE TITLE
1.0.6 and 1.0.5 not working

### ISSUE THREAD

**Issue by kranix0** [samartzidis/WinAppleKey#34]
Continuing from #30, the latest version that works for me is 1.0.4. With 1.0.5 and 1.0.6, I don't see WinAppleKey in Device Manager.

I couldn't work out how to download previous releases, but fortunately I still had an old copy in my Recycle Bin.

**Comment by JeffyOLOLO** [comment]
I have the same issue.
I builded on VS 2017 with SDK/WDK 1809 (17763) version and it doesn't work :(
I'm on 17763 build of Windows.
Also tried in VS 2019 with 1903.

**Comment by samartzidis** [comment]
Source has been migrated to VS2019 and the resulting build 1.0.7 should be installing and working properly.
