### ISSUE TITLE
Registry keeps resetting to default values

### ISSUE THREAD

**Issue by brhsiao** [samartzidis/WinAppleKey#35]
SwapAltCmd and SwapFnCtrl keep on resetting to the default values (0 and 1 respectively) without my interference. I'm not sure when this is happening -- on restart? on keyboard reconnect?

*Edit:* I figured out when it happens: when I switch from USB to Bluebooth or vice versa.

Where in the code does this happen exactly? I looked through it and it only seems to ever read from the registry, not write.

**Comment by brhsiao** [comment]
I figured out when it happens. If I switch from USB to Bluebooth or vice versa  the settings reset to their default.

When does this happen exactly? I looked at the code and it only ever reads from the registry, not writes.

**Comment by lukiolee** [comment]
Yeah i have the same problem bro

Brandon Hsiao <notifications@github.com>于2019年6月22日 周六22:39写道：

**Comment by reznikartem** [comment]
Make PR with fix for this problem

https://github.com/samartzidis/WinAppleKey/pull/39

Attach zip file with Setup binary, if you cant compile it by yourself

[Setup.zip](https://github.com/samartzidis/WinAppleKey/files/4010276/Setup.zip)

**Comment by samartzidis** [comment]
Should be now fixed in 1.0.7
