### ISSUE TITLE
Driver signature enforcement disabled

### ISSUE THREAD

**Issue by erttu** [samartzidis/WinAppleKey#38]
I was wondering that why it is not possible to install these drivers with Windows' driver signature enforcement disabled? Isn't it basically the same thing as doing the installation in Test Mode? I do not know too much about the differences between these two methods and would be highly interested to hear if there is some crucial difference which makes Test Mode the only option. 

Thanks :)

**Comment by samartzidis** [comment]
I am not sure of the exact internal implementations of those 2 boot options but in Windows 10 it seems that setting **nointegritychecks** to **on** does not have any effect in allowing unsigned or testsigned drivers. Setting **testsigning** mode is the only working option.
Some user mentions this, which basically justifies this observation: https://stackoverflow.com/a/50156020
