### ISSUE TITLE
Keyboard reverts back to default key setup when wired

### ISSUE THREAD

**Issue by RailRanger** [samartzidis/WinAppleKey#4]
If I have the keyboard connected wirelessly it works just fine. However as soon as I plug it back in the keys all revert to the defaults. Is it possible for the program to work in wired mode?

**Comment by samartzidis** [comment]
Thanks for letting me know. Planned to fix.

**Comment by vaevictis** [comment]
I have the same issue. I can't test it without wire as I don't have a bluetooth chip with my PC (I actually use the keyboard most of the time with my laptop).

**Comment by samartzidis** [comment]
This is now fixed in release 1.0.3. Thanks.
