### ISSUE TITLE
not working on apple magic keyboard model A1314

### ISSUE THREAD

**Issue by ryanhardt41** [samartzidis/WinAppleKey#46]
I turned on everything that was required, and I have installed the driver with no problems, However, even after a reboot, the keys were still not re-mapped and was still using the old keybinds. I am using the model A1314 magic keyboard, the model with the old scissor switches (not the new butterfly switches or the new, revamped scissor switches).

**Comment by samartzidis** [comment]
Hi. The driver is for the Apple Magic Keyboard (model A1644).
