### ISSUE TITLE
Why remove support for Apple Wireless Keyboard (A1314)?

### ISSUE THREAD

**Issue by kranix0** [samartzidis/WinAppleKey#47]
I see that the Apple Wireless Keyboard (model A1314) is no longer supported (https://github.com/samartzidis/WinAppleKey/commit/467c1cff7e1b0c2ef4fa45cc31b130b0db2d6972 and #46). I have version 1.0.4 working great with my A1314. So why the change? Does that mean I'm stuck at 1.0.4?

Thanks.

**Comment by samartzidis** [comment]
Yes sorry, it was buggy and I did not have the time to maintain.
