### ISSUE TITLE
Huge Thanks!

### ISSUE THREAD

**Issue by HouzuoGuo** [samartzidis/WinAppleKey#48]
My colleagues were complaining that my mechanical keyboard was too loud over microphone, actually I didn't like the keyboard that much anyways as the keys are too tall for my taste.

I was a Macbook user about a year ago and really loved the keyboard. Couple of hours ago I scavaged this slightly used, good as new apple magic keyboard from miscellaneous section of local electronics store, was happy to bring it back home, but soon realised that it doesn't even have a page up and down key,

Gladly I found your project :) and it's working beautifully.

**Comment by HouzuoGuo** [comment]
BTW - this is kinda weird. Ctrl+LShift+T doesn't work in Chrome and Edge, though Ctrl+RShift+T works.

Ctrl+LShift+Delete(eject) works though.

**Comment by samartzidis** [comment]
Thank you @HouzuoGuo :) I am aware of the Ctrl(fn)+LShift+T thing. Strangely it seems to be an issue with the keyboard hardware itself not liking this particular combination.

**Comment by HouzuoGuo** [comment]
decades long rivalry between PC and MAC haha.. thanks!
