### ISSUE TITLE
Is testsigning still necessary?

### ISSUE THREAD

**Issue by verity-s** [samartzidis/WinAppleKey#50]
I would love to use this driver on Windows 10, but since it's a work machine the test mode is not an option. I recently came across and am using the Magic Trackpad windows driver that was installed successfully and was wondering if the same approach would work? Sorry, I have no knowledge of the driver signing so apologies if this is a silly question :)

https://github.com/imbushuo/mac-precision-touchpad

Thanks for all your hard work on this!

**Comment by samartzidis** [comment]
No I can't do the same. I suspect that he has bought a code signing certificate and signed his binaries with it. But for your particular case, and if you dont mind the extra little device attached to your PC, take a look at my RaspiKey project [here](https://github.com/samartzidis/RaspiKey).
