### ISSUE TITLE
can you tell it not to swap ctrl and fn keys

### ISSUE THREAD

**Issue by myusrn** [samartzidis/WinAppleKey#51]
Can you tell it not to swap ctrl and fn keys given i'm used to msft ergo desktop keyboard and lenovo thinkpad x1 keyboards where on left side its fn | ctrl | win | alt and on right side of space bar its alt | context menu / print screen remapped to win | ctrl?

**Comment by samartzidis** [comment]
To enable/disable the Fn-Ctrl key swapping: https://github.com/samartzidis/WinAppleKey#driver-settings
