### ISSUE TITLE
Keyboard repeating keys after upgrade to 1.0.8

### ISSUE THREAD

**Issue by joowani** [samartzidis/WinAppleKey#52]
Occasionally my keyboard will repeat random keys (two characters at the time most frequently) . It seems to be happening after upgrade to 1.0.8, but I'm having a hard time reproducing it. Example: "push" -> "pushsh".

Has anyone else had a problem? Using model A1644 (wired)

**Comment by samartzidis** [comment]
Thank you @joowani I was able to occasionally reproduce it when typing too fast. I will investigate further.

**Comment by samartzidis** [comment]
https://github.com/samartzidis/WinAppleKey/releases/tag/v1.0.9
