### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by scorpio2k2** [samartzidis/WinAppleKey#6]
Hi,
I compiled the exe and installed it but nothing happens.. 
no keymapping

**Comment by samartzidis** [comment]
Hi, I have heard of that issue from a couple of other users here with the A1644 (new) model in wireless setup. I am investigating this.

**Comment by scorpio2k2** [comment]
oh.. I'm waiting and I'm trying to investigate myself.

**Comment by scorpio2k2** [comment]
hi,
Question: can you share a compiled version to see if it works? 
Thanks

**Comment by samartzidis** [comment]
The compiled version is already offered in the project page. If you click on "releases" you will find it. I doubt that there is a problem with your own compiled version though. There most likely is an issue with my code that needs fixing.

**Comment by samartzidis** [comment]
Hi Valentin,

There already is a compiled version of the software if you click on
"releases" on the main page.

Thank you.

**Comment by scorpio2k2** [comment]
The issue was on my side. It works with the file from "releases".

Thank you

**Comment by samartzidis** [comment]
That's good news! Thanks for letting me know.
