### ISSUE TITLE
Ctrl + LeftShift + T doesn't work.

### ISSUE THREAD

**Issue by Eterad** [samartzidis/WinAppleKey#7]
Hi,

When trying to reopen closed tab using LeftShift doesn't work. It does work however with RightShift.

Best,
Adam

**Comment by Hubro** [comment]
I just noticed this too. What a weird bug :)

**Comment by simplecoder** [comment]
Yes, I noticed this as well. Unfortunately it is a commonly used key combination too.

**Comment by vogler** [comment]
Is this still the case? For me it works fine (A1314 and A1644).

**Comment by WireCrazii** [comment]
@vogler Yes, this bug still exists in both A1314 and A1644(for me).

**Comment by samartzidis** [comment]
This seems to be a hardware issue with the Apple keyboard and not a driver fault. 

Even without the driver installed when you press the (real)Fn+LShift+T keys simultaneously, the keyboard generates a Keyboard Rollover Error as if you're basically pressing more than 5 keys simultaneously, which is that the keyboard hardware can handle (which is weird as it only happens with that specific 3-key combination). I am closing this for now, unless Apple decides to look into this maybe? :}

The alternative as mentioned elsewhere is using the right shift instead.
