### ISSUE TITLE
Swap Left Alt with Left Win?

### ISSUE THREAD

**Issue by Hubro** [samartzidis/WinAppleKey#8]
Already this driver is a godsend, but I'm missing one thing;

Is it possible to swap the left windows and left alt key, in order to correspond with regular windows keyboards?

As an unrelated follow-up question, are you planning to properly sign the driver so it can be installed without Test Mode?

**Comment by samartzidis** [comment]
This is now addressed in release 1.0.3. Thanks.

**Comment by Hubro** [comment]
Fantastic! I'll test it out tomorrow or on Tuesday.

**Comment by Hubro** [comment]
Works flawlessly! Thanks!

**Comment by elgydium** [comment]
@samartzidis Ekanes kali douleia Giorgo, omws polla pexnidia exoune problima me to Win Test Mode. Any workaround that?
